# Usa Node.js compatible con tus dependencias
FROM node:24

WORKDIR /app

# Copia los archivos del proyecto
COPY . .

# Instala dependencias y construye el proyecto
RUN npm install
RUN npm run build
# Expone el puerto que Railway espera
EXPOSE 4173

# Comando para servir el sitio
CMD ["npm", "run", "preview"]