# Etapa de construcción
FROM node:24 AS builder
WORKDIR /app

# Copia los archivos del proyecto
COPY . .

# Instala dependencias y construye el proyecto
RUN npm install
RUN npm run build

# Etapa de producción con Nginx
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html

