# Etapa de construcción
FROM node:18 AS builder
WORKDIR /app

# Copia los archivos del proyecto
COPY . .

# Instala dependencias y construye el proyecto
RUN npm install
RUN npm run build

# Etapa de producción con Nginx
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html

# Copia configuración básica de Nginx (opcional)
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]